### ISSUE TITLE
Color Scheme / Theme

### ISSUE THREAD

**Issue by steven-murray** [halomod/TheHaloMod-SPA#106]
I like the layout already. However, the colors could use some tweaking. 

I'd like the top panel to be dark -- some grey-black (around #555555. The rest of the colors could be something like a Monokai pallete. I like the pink used in the range sliders. 

I think the current blue is a bit bleh, so I'd change that.

Also, not sure, but it *might* be nice to set the background of the sidebar in the form to another color than white?

Also, the top navbar, "The Halo Mod" should be "TheHaloMod".

**Comment by steven-murray** [comment]
The colors currently used in the logo are #343a40, #b1e6d0 and #888988. Might be useful to follow that kind of scheme.

**Comment by steven-murray** [comment]
Just discovered palettable. Here's a scheme I like: https://www.palettable.io/B1E6D0-343A40-888988-FF6188-FC9867

Not sure if it covers all the bases. Perhaps an extra standardish blue would be good.

**Comment by steven-murray** [comment]
Here's a full theme with hexes, similar to the above: 
![HMF](https://user-images.githubusercontent.com/1272030/112697722-6d259800-8e45-11eb-96a9-04180cd265c5.png)

**Comment by aneuhold** [comment]
@steven-murray the framework that we are using to build the site supports two colors as a theme. A primary color and an accent color. By default the primary is blue and the accent is red. The theme was updated to have the light blue you had selected and the dark gray, mainly because those were the colors of the logo. See below for screenshots of the light and dark variant:

Light variant:
![image](https://user-images.githubusercontent.com/17774559/113072537-1b9a4780-917c-11eb-94a5-bef43f558572.png)

Dark variant:
<img width="1676" alt="Screen Shot 2021-03-30 at 5 15 58 PM" src="https://user-images.githubusercontent.com/17774559/113072491-fe657900-917b-11eb-80ec-0a00e2fe438c.png">

Please ignore the legend for the plot for now, that will be fixed. 

It seems that only two colors are allowed because it uses calculations to find out the best color offset for the other colors throughout the application, and having more than two colors would likely throw that off. But there are a few questions:

1. If you had to choose two colors what would they be out of the above color palette? Primary and accent (color of buttons and things are the accent). Also note that those two colors can be different between the dark and light versions of the site. 
2. If more than 2 colors are preferred, where would you like the other colors to be? Or otherwise, we can work on just finding places for them perhaps. Like the background or text colors, etc. 
3. Are there any other 2 color combos you want screenshots of really quick? It is fast to do so it won't take time at all.

**Comment by aneuhold** [comment]
Also does there happen to be an `.svg` version of the logo somewhere? Just copied over the other assets from `TheHaloMod` but it didn't seem to have an SVG of that logo. It would help quite a bit with the load times because right now that is one of the biggest files it needs to load.

**Comment by steven-murray** [comment]
Thanks @aneuhold for the explanation. 

1. I think the bluey green is good for the primary. Perhaps the pink as accent? I like the dark version, but not sure if I'm that brave :-) Could you send also a shot of the forms page with these variants?
2. If we were to use another color as well, I'd go for the dark grey at the left of the color pallete above. This is close to the background in the dark mode. In light mode, perhaps the primary could be that color, and the accent the green-blue. Or, if the accent could stay as the pink, we could use the green-blue elsewhere (not sure where).
3. Let's try a light version with Primary: dark grey, accent: orange, and a dark version with Primary: blue-green, Accent: pink.

I don't think I have an SVG of the logo, which is weird come to think of it. That's OK, I'll just design a new set of logos and send them over.

**Comment by aneuhold** [comment]
Hi Steven, here are some screenshots below:

Bluish green primary and pink accent - light mode - Home Page:

![image](https://user-images.githubusercontent.com/17774559/113196543-7aad9a00-9218-11eb-85b8-c0a47d224fa5.png)

Bluish green primary and pink accent - light mode - Forms Page:

![image](https://user-images.githubusercontent.com/17774559/113196693-a597ee00-9218-11eb-898e-0eae1dfd49a1.png)

Bluish green primary and pink accent - dark mode - Home Page:

![image](https://user-images.githubusercontent.com/17774559/113196890-db3cd700-9218-11eb-8c00-b3207bc04616.png)

Bluish green primary and pink accent - dark mode - Forms Page:

![image](https://user-images.githubusercontent.com/17774559/113196953-eabc2000-9218-11eb-97ff-d34ca200df8e.png)

Dark grey primary and orange accent - light mode - Home Page:

![image](https://user-images.githubusercontent.com/17774559/113197513-9f564180-9219-11eb-9012-0e9c99940307.png)

Dark grey primary and orange accent - light mode - Forms Page:

![image](https://user-images.githubusercontent.com/17774559/113197574-b301a800-9219-11eb-8b34-c7c19146203b.png)

Bluish green primary and pink accent - dark mode - See above ⬆️

Also, sounds good about the SVG. That will be helpful. The form layout is still pending, so note that that is the current layout before changes that will be made according to the other issues.
