### ISSUE TITLE
Comoving R Range

### ISSUE THREAD

**Issue by aneuhold** [halomod/TheHaloMod-SPA#168]
This is in reference to the second to last point made in [this comment](https://github.com/halomod/TheHaloMod-SPA/pull/166#pullrequestreview-652543265).

@steven-murray assuming this is in reference to the plotting on the client side, when using the logarithmic scale, the default is base 10, according to the plotting library's documentation on the `scaleLog` function [here](https://github.com/d3/d3-scale/blob/v3.3.0/README.md#scaleLog). The code on the client is here:

https://github.com/halomod/TheHaloMod-SPA/blob/3c4cc4cb3e73ff1079aae7ee487649f33ec10de6/client/src/utils/plot.js#L174-L181

So, even if the scale wasn't logarithmic, it should still show all values being generated by the server aka the halomod library because it uses the maximum x and minimum x sent over from the server to set the bounds for the plot. 

With that said, do you have an idea on how to fix this or where to look?

**Comment by steven-murray** [comment]
@aneuhold, it's not so much with the plotting, but with the input from the form. `halomod` expects you to give it `rmin` and `rmax`. On the form, these are input as a range slider that shows logarithmic versions of these. When getting "cleaned" from the form, I expect we're taking the `exp` of the values rather than a power of 10.

**Comment by aneuhold** [comment]
@steven-murray Ah, it is because it wasn't converting it at all. Are there other values that need to be converted on the client side? If this was expected of a lot of the parameters that say "log" in some way, then some relatively sweeping change will need to be made to account for that. Might not take long, but a lot will need to be addressed. 

Although after looking at the generated backend constants, it seems that most, if not all, of the constants that say "log" are already pretty low values, making it seem that the backend handles that for those. Is this a one-off case?

**Comment by aneuhold** [comment]
One other thing to note is that this could quickly be fixed by changing the name of the range slider to something that doesn't say "log" so as to not mislead the user, then set the min and max to -100 to 100 or whatever the actual min and max without conversion is. If that isn't wanted though, then definitely happy to configure this as desired.

**Comment by steven-murray** [comment]
I think this might just be for the comoving r, and its because halomod itself accepts absolute values of rmin and rmax, not their log values (the M and k values are expected to be passed in pre-logged). It's better to select these values in log-space on the form, because the lower end should be something like 0.01 and the upper end about 150, but its hard to have an accuracy of 0.01 when going up to 150. In log-space, this is just like -3 to 3.
